### ISSUE TITLE
Add support for 1.13

### ISSUE THREAD

**Issue by eirikh1996** [WinX64/SmartSignEditor#1]
Hello. Could you please update this plugin to 1.13?

Log output when running it on 1.13:
[15:56:27 INFO]: [SmartSignEditor] Enabling SmartSignEditor v2.5.2.3
[15:56:27 ERROR]: [SmartSignEditor] The current server version is not supported!
[15:56:27 ERROR]: [SmartSignEditor] Your current version is v1_13_R2. This is a newer version that still not supported. Ask the author to provide support for it!
[15:56:27 INFO]: [SmartSignEditor] Disabling SmartSignEditor v2.5.2.3

Thanks

**Comment by WinX64** [comment]
The current version on the main branch already has support for both 1_13_R1 and 1_13_R2, however, it still lacks some previous features since I am in the middle of refactoring great part of the project.

I'm avoinding posting an update due to this factor, but will sort this out as soon as possible.

In the mean time if you want, you can compile and use the latest version yourself, but be aware that it may break due to incomplete changes on the configuration system.

**Comment by Malachiel87** [comment]
any news about this? :(

**Comment by WinX64** [comment]
As of now, the plugin supports all available 1.13 and 1.14 versions.

Sorry for the time it took, there have been some changes on the API since the release of 1.13, and some features needed for the plugin to work were completely broken with the release of 1.14. I needed some time to work things out on how to handle these 2 new versions (but it was mostly lack of available time to do it).

You can check out version 2.6.0 [here](https://www.spigotmc.org/resources/smartsigneditor.24594/update?update=294799).
